### PR TITLE
init unit tests

### PR DESCRIPTION
**Pull request by lastlink**
@imfx77

### CODE REVIEW

**Comment by imfx77** [comment]
@lastlink 
I haven't played yet with automating unit tests via GitHub actions. So I am not really aware what the code you propose is doing and how to handle the errors that were triggered by it. Some assistance would be appreciated.

**Comment by lastlink** [comment]
@imfx77 I'd remove approval from the github action workflows unless they are using secrets or limited cost. I usually only lock down for deploy actions. Nice thing about unit tests is that you can block prs if the tests fail giving higher confidence of stuff not breaking before you manually test.

To test kanboard you need to clone their whole project, then clone your plugin into the plugin folder, have php installed, run composer install and run the unit test arguments for the database target. In github action it uses the kanboard container that has this embedded to some extend

**Comment by lastlink** [comment]
@imfx77 I follow a dev branch policy where all prs get merged into dev and I can then test that manually before merging into master and doing a release. Helps with open contribution and seeing all changes at once. You do need to make dev your main branch if you do this, so contributors auto do prs from dev. But it's preference and how active you are in maintaining the repo.

**Comment by lastlink** [comment]
@imfx77 
github_status_checks

**Comment by imfx77** [comment]
making a dev branch, will try to configure sensible protection rules to allow for contribution

**Comment by lastlink** [comment]
@imfx77 I've updated target to dev. Anything holding back this pr getting merged in?

**Comment by imfx77** [comment]
should i remove this check to allow automatic merge?
image

**Comment by lastlink** [comment]
> @imfx77 after merging this branch in then require the unit tests **(probably leave required approvals unchecked**) then any new prs won't be able to be merged in if unit tests are failing github_status_checks

I made a comment here to leave it unchecked. I might recommend leaving it on in master so you approve anything for final release.

**Pull request merged**
